name: Worlds
version: '${project.version}'
main: de.murmelmeister.worlds.Worlds
api-version: 1.19
authors: [ Murmelmeister ]
description: A world system for Minecraft servers.
website: https://www.youtube.com/Murmelmeister

commands:
  worlds:
    usage: /<command> <create|delete|tp|import> <worldName>
    description: Manager command for worlds.